version: '2'
services:
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  connect:
    image: docker-registry.echoing.tech/bigdata/debezium/connect:${DEBEZIUM_VERSION}
    container_name: connect
    ports:
      - 8083:8083
    links:
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=47.101.175.74:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=cdc_connect_configs
      - OFFSET_STORAGE_TOPIC=cdc_connect_offsets
      - STATUS_STORAGE_TOPIC=cdc_connect_statuses
#  debezium-ui:
#    image: debezium/debezium-ui:${DEBEZIUM_VERSION}
#    container_name: debezium-ui
#    ports:
#      - "8080:8080"
#    environment:
#      - KAFKA_CONNECT_URIS=http://127.0.0.1:8083
#    depends_on:
#      - connect
#    networks:
#      - ui-network
#networks:
#  ui-network:
#    external: false