version: '2'
services:
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  connect:
    image: docker-registry.echoing.tech/bigdata/debezium/connect:${DEBEZIUM_VERSION}
    container_name: connect
    ports:
      - 8083:8083
    links:
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=47.101.175.74:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
# curl -i -X POST -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:8083/connectors/ -d @source.json